name: my first github action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      

      - name: install dependencies
        uses: actions/setup-python@v3

      - name: set pythonpath
        run: export pythonpath="githubactionsdemo"

      - name: execute command
        run: |
          python3 src/main.py

      
